services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - GOOGLE_API_KEY=your_gemini_api_key
      - E2B_API_KEY=your_e2b_api_key
    restart: always

  frontend:
    build:
      context: ./frontend-app
    ports:
      - "3000:80"
    depends_on:
      - backend

